# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
#' @noRd
cpp_CCA <- function(Xo, Yo, normalize, verbosity) {
    .Call(`_PACA_cpp_CCA`, Xo, Yo, normalize, verbosity)
}

#' @export
#' @noRd
cpp_selectK <- function(X, Y, normalize, threshold, verbosity) {
    .Call(`_PACA_cpp_selectK`, X, Y, normalize, threshold, verbosity)
}

#' @export
#' @noRd
cpp_PACA <- function(Xo, Yo, k, normalize, retCCA, verbosity) {
    .Call(`_PACA_cpp_PACA`, Xo, Yo, k, normalize, retCCA, verbosity)
}

#' @export
#' @noRd
cpp_autoPACA <- function(Xo, Yo, normalize, retCCA, threshold, verbosity) {
    .Call(`_PACA_cpp_autoPACA`, Xo, Yo, normalize, retCCA, threshold, verbosity)
}

#' @export
#' @noRd
cpp_prcomp <- function(X, center, scale, rank, tol, verbosity) {
    .Call(`_PACA_cpp_prcomp`, X, center, scale, rank, tol, verbosity)
}

#' @export
#' @noRd
cpp_rPACA <- function(X, Y, k, niter, batch, rank, normalize, verbosity) {
    .Call(`_PACA_cpp_rPACA`, X, Y, k, niter, batch, rank, normalize, verbosity)
}

normalizeCPP <- function(x, inplace) {
    .Call(`_PACA_normalizeCPP`, x, inplace)
}

