# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

normalizeCPP <- function(x, inplace = TRUE) {
    .Call(`_PACA_normalizeCPP`, x, inplace)
}

#' @export
#' @noRd
cpp_prcomp <- function(X, center = TRUE, scale = FALSE, rank = NULL, tol = NULL, verbosity = 1L) {
    .Call(`_PACA_cpp_prcomp`, X, center, scale, rank, tol, verbosity)
}

#' @export
#' @noRd
cpp_CCA <- function(Xo, Yo, normalize = TRUE, verbosity = 1L) {
    .Call(`_PACA_cpp_CCA`, Xo, Yo, normalize, verbosity)
}

#' @export
#' @noRd
cpp_selectK <- function(X, Y, normalize = TRUE, threshold = 10.0, verbosity = 1L) {
    .Call(`_PACA_cpp_selectK`, X, Y, normalize, threshold, verbosity)
}

#' @export
#' @noRd
cpp_PACA <- function(Xo, Yo, k, normalize = TRUE, retCCA = FALSE, verbosity = 1L) {
    .Call(`_PACA_cpp_PACA`, Xo, Yo, k, normalize, retCCA, verbosity)
}

#' @export
#' @noRd
cpp_autoPACA <- function(Xo, Yo, normalize = TRUE, retCCA = FALSE, threshold = 10.0, verbosity = 1L) {
    .Call(`_PACA_cpp_autoPACA`, Xo, Yo, normalize, retCCA, threshold, verbosity)
}

